lib/home_inventory_graphql/router.ex
defmodule HomeInventoryGraphQL.Router do
  use Plug.Router

  defmodule GraphQL do
    use Plug.Router

    plug(:match)
    plug(:dispatch)

    forward("/",
      to: Absinthe.Plug,
      init_opts: [
        document_providers: {HomeInventoryGraphQL, :document_providers},
        json_codec: Jason,
        schema: HomeInventoryGraphQL.Schema
      ]
    )
  end

  plug(HomeInventoryGraphQL.Plugs.Context)

  plug(:match)
  plug(:dispatch)

  forward("/graphql", to: GraphQL)

  match(_, do: conn)
end

lib/home_inventory_web/router.ex
defmodule HomeInventoryWeb.Router do
  use HomeInventoryWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:session)
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {HomeInventoryWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(HomeInventoryWeb.ContentSecurityPolicy)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", HomeInventoryWeb do
    pipe_through(:browser)

    get("/", PageController, :index)
    resources("/locations", LocationController)
    resources("/items", ItemController)
  end

  # Other scopes may use custom stacks.
  # scope "/api", HomeInventoryWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through(:browser)

      live_dashboard("/dashboard", metrics: HomeInventoryWeb.Telemetry)
    end
  end

  defp session(conn, _opts) do
    opts =
      Plug.Session.init(
        store: :cookie,
        key: Application.get_env(:home_inventory, __MODULE__)[:session_key],
        signing_salt: Application.get_env(:home_inventory, __MODULE__)[:session_signing_salt]
      )

    Plug.Session.call(conn, opts)
  end
end

lib/home_invetory_health/router.ex
defmodule HomeInventoryHealth.Router do
  use Plug.Router

  defmodule Health do
    use Plug.Router

    plug(:match)
    plug(:dispatch)

    forward(
      "/",
      to: PlugCheckup,
      init_opts:
        PlugCheckup.Options.new(
          json_encoder: Jason,
          checks: HomeInventoryHealth.checks(),
          error_code: HomeInventoryHealth.error_code(),
          timeout: :timer.seconds(5),
          pretty: false
        )
    )
  end

  plug(:match)
  plug(:dispatch)

  forward("/health", to: Health)

  match(_, do: conn)
end

lib/home_inventory_web/views/layout_view.ex
defmodule HomeInventoryWeb.LayoutView do
  use HomeInventoryWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/home_inventory_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/home_inventory_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/home_inventory_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Home Inventory" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header class="container is-max-desktop">
      <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a class="navbar-item" href={Routes.page_path(@conn, :index)}>
            <h1 class="is-size-2">Home Inventory</h1>
          </a>

          <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start">
            <%= link "Locations", to: Routes.location_path(@conn, :index), class: "navbar-item" %>
            <%= link "Items", to: Routes.item_path(@conn, :index), class: "navbar-item" %>
          </div>
          <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
          <div class="navbar-end">
            <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home), class: "navbar-item" %></li>
          </div>
          <% end %>
        </div>
      </nav>
    </header>
    <section class="section container is-max-desktop">
      <%= @inner_content %>
    </section>
  </body>
</html>